### PR TITLE
Updates for windows and to use and pin the latest ACA-Py - 0.4.2 in the Dockerfile

### PR DESCRIPTION
**Pull request by swcurran**

### CODE REVIEW

**Comment by swcurran** [comment]
The .gitignore changes are needed to get the agents running on Windows - handling the line endings.

The other two changes are to remove the reliance on the Sovrin version of indy and to pin the version to a known (0.4.2 - current) ACA-Py.  Not sure if you want to do that, or always get the latest from PyPi.

We're assuming that the reliance on the Sovrin branch is no longer needed (didn't work for me on Windows or Linux) and that we don't want to use other than a released version on PyPi.

**Comment by dbluhm** [comment]
The branch on the Sovrin Foundation fork is being used because of the problem described in this PR I opened a while back: https://github.com/hyperledger/aries-cloudagent-python/pull/355

We need a better solution than using the credential exchange records but until we have that, the SF demo branch is essentially v0.4.2 with a patch that prevents the deletion of those exchange records.

**Comment by swcurran** [comment]
Sounds good. I'll try to push that PR through the ACA-Py process. Sorry it took so long.  I had something odd happen on Linux the first time I tries the demo and by going to the ACA-Py version I got it to work, but I suspect it was something else.

I left in the changes that I think are necessary for running on Windows, and the change to update to the latest indy-sdk.

On Linux, the start process seems solid, but on Windows we have seen that on one machine, most of the time only one agent gets connected.  When we open the agents, most of the time we get the list of protocols in the menu on one agent, but on the second, we get an empty list. I'm thinking it is because of the connection in ACA-Py not being marked as "connected", but not that's just a guess. It may be a timing issue as a couple of times we did get it to work, but most of the time we didn't -- all test runs on one laptop so YMMV.  We tried on different versions of indy-sdk before/after our changes to the ACA-Py version.

**Comment by swcurran** [comment]
Daniel, just tried running this on Linux out of the box and again encountered the error that caused me to flip from the Sovrin repo to ACA-Py.  It looks like something is broken in the Sovrin branch. This is fixed when switching to the ACA-Py repo as the source of the pip install.

```
agent-alice_1  | 2020-02-25 16:16:55,185 aries_cloudagent.commands.start ERROR Exception during startup:
agent-alice_1  | Traceback (most recent call last):
agent-alice_1  |   File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aries_cloudagent/commands/start.py", line 74, in init
agent-alice_1  |     await startup
agent-alice_1  |   File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aries_cloudagent/commands/start.py", line 26, in start_app
agent-alice_1  |     await conductor.setup()
agent-alice_1  |   File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aries_cloudagent/core/conductor.py", line 65, in setup
agent-alice_1  |     context = await self.context_builder.build()
agent-alice_1  |   File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aries_cloudagent/config/default_context.py", line 48, in build
agent-alice_1  |     await self.load_plugins(context)
agent-alice_1  |   File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aries_cloudagent/config/default_context.py", line 161, in load_plugins
agent-alice_1  |     plugin_registry.register_plugin(plugin_path)
agent-alice_1  |   File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aries_cloudagent/core/plugin_registry.py", line 39, in register_plugin
agent-alice_1  |     mod = ClassLoader.load_module(module_name)
agent-alice_1  |   File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aries_cloudagent/utils/classloader.py", line 70, in load_module
agent-alice_1  |     return import_module(mod_path, package)
agent-alice_1  |   File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/importlib/__init__.py", line 126, in import_module
agent-alice_1  |     return _bootstrap._gcd_import(name[level:], package, level)
agent-alice_1  |   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
agent-alice_1  |   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
agent-alice_1  |   File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
agent-alice_1  |   File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
agent-alice_1  |   File "<frozen importlib._bootstrap_external>", line 678, in exec_module
agent-alice_1  |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
agent-alice_1  |   File "/home/indy/acapy_plugin_toolbox/__init__.py", line 3, in <module>
agent-alice_1  |     from .group.all import setup
agent-alice_1  |   File "/home/indy/acapy_plugin_toolbox/group/all.py", line 11, in <module>
agent-alice_1  |     from ..holder import MESSAGE_TYPES as HOLDER_MESSAGES
agent-alice_1  |   File "/home/indy/acapy_plugin_toolbox/holder.py", line 11, in <module>
agent-alice_1  |     from aries_cloudagent.protocols.issue_credential.v1_0.routes import (
agent-alice_1  | ImportError: cannot import name 'V10CredentialProposalRequestMandSchema'

```

**Comment by dbluhm** [comment]
There is a deficiency in the Dockerfile we're using right now where changes in the remote branch pointed to by that pip install command cannot invalidate the docker image cache. I am guessing an older cached image is being used. To work around this, I've cleared old docker images and rebuilt.

**Comment by dbluhm** [comment]
> There is a deficiency in the Dockerfile we're using right now where changes in the remote branch pointed to by that pip install command cannot invalidate the docker image cache.

It would probably be better if we pointed to a specific commit. That way when changes need to be made, the Dockerfile can be updated to point to the new commit which would properly invalidate the cache and cause the correct version to be built.

**Comment by swcurran** [comment]
That's weird.  I don't recall using that before.  Clearing the docker cache is a heavyweight thing to do - it would be really helpful not to do that.

Perhaps add a tag to the desired commit, and update it as needed?  Or just the commit. :-)

**Pull request merged**
